### ISSUE TITLE
关于悬浮窗显示了两个的问题

### ISSUE THREAD

**Issue by yuqianglianshou** [shenzhen2017/EasyFloat#10]
作者你好，我是一个Android开发者，首先感谢你的开源项目。
这里描述一个非常令人费解的问题。

页面上悬浮窗的实例显示了两个。

需求：
首页MainActivity 5个tab栏，viewpager2 + fragment实现，需要在跳转到第三个tab时显示悬浮窗，跳转到其他tab页或进入到其它页面关闭即可。

逻辑：
在MainActivity  中的 onResume() 中 判断是第三个tab 显示悬浮窗。在 onPause() 中关闭悬浮窗。
在viewpager切换到第三个 tab显示悬浮窗，切换到其它的关闭悬浮窗。

现象：
目前可知项目使用了大于几千次，出现了两次实例出现了两次的异常情况，亲眼所见，且后台无异常信息。异常时，一个实例一直存在，切换页面，拖动，点击事件等此实例都是没问题的，且 切换页面后可以记录位置，可证明是同一个实例，另一个跟随正常逻辑显示和关闭。即当切换到第三个tab栏时，会显示两个（应该只有一个）两个都拥有正常功能，其它页面一直存在一个（不应该有）。

操作：
随意点击页面切换，跳转，发现 不应该显示的页面显示了一个，切换到应该显示的第三个页面，看到了两个。

通过代码可知悬浮窗是单例的，我通过代码不断执行show()方法打开 实例也只会存在一个，所以出现了这种情况令我很头疼。

**Comment by RicardoJiang** [comment]
可以打断点看看FloatingView attach有没有执行多次？
还有就是如果是首页用的是ViewPager的话，我知道Fragment可见时会调用onResume，不可见时会调用onPause
这样在Fragment里处理显示隐藏逻辑就可以了，不用在Activity中多处判断
ViewPager2应该是类似的？

**Comment by yuqianglianshou** [comment]
多谢指导，实现方式我们且不谈，描述使用场景的意义在于方便判断是否是我的“代码环境”的问题。我测试 通过点击事件不断的打开和关闭悬浮窗，并没有触发这个异常问题，我觉得问题的本质在于在什么条件下会导致单例的代码“失效”，这是我最大的疑问😁

**Comment by RicardoJiang** [comment]
这个我也不太清楚，复现不出来，所以比较难定位
