### ISSUE TITLE
悬浮窗宽度移动问题。

### ISSUE THREAD

**Issue by lhj1079947827** [shenzhen2017/EasyFloat#2]
在移动悬浮窗口时移动的宽度没有做限制，导致可以把悬浮窗口移动屏幕外这样子，滑动感觉很难受。看了一下你的源码。只是做了高度限制，没有做宽度限制，应该在宽度哪里增加判断如图[
![image](https://user-images.githubusercontent.com/20966610/118767396-45d0d180-b8b0-11eb-87f5-f8d5552d0e44.png)
](url)

**Comment by shenzhen2017** [comment]
已处理，谢谢提醒
