### ISSUE TITLE
不支持java

### ISSUE THREAD

**Issue by wupengwp** [shenzhen2017/EasyFloat#3]

**Comment by shenzhen2017** [comment]
![image](https://user-images.githubusercontent.com/18047645/119358314-115b7c00-bcdb-11eb-9282-94747a1939ec.png)
支持啊，如图所示
你那边有什么问题吗？麻烦发下报错信息，谢谢

**Comment by shenzhen2017** [comment]
![image](https://user-images.githubusercontent.com/18047645/119358314-115b7c00-bcdb-11eb-9282-94747a1939ec.png)
支持啊，如图所示
你那边有什么问题吗？麻烦发下报错信息，谢谢

**Comment by wupengwp** [comment]
支持的，现在有个问题，我只在一个页面显示悬浮，子啊onDestroy中dismiss，消失的有点慢

**Comment by shenzhen2017** [comment]
可以改成在onStart中添加，在onStop中dismiss,onDestroy回调很慢的
