### ISSUE TITLE
开源的库可以在码云备份一个，github 访问很慢的~

### ISSUE THREAD

**Issue by xuyingke** [shenzhen2017/EasyFloat#4]
github 的库我要下载都会在码云先同步一份，在下载。否则一上午都下载不下来。

**Comment by xuyingke** [comment]
这个方案就全靠交互是否接受。切换的效果并没有申请悬浮窗权限的优雅。
在之前做悬浮窗时考虑过这个方案，就是交互不接受，换了需 WindowManger 的方案。

**Comment by shenzhen2017** [comment]
恩，切换效果的确有一些差异，得看具体需求了
已同步到码云：https://gitee.com/shenzhen2017/EasyFloat
谢谢提醒。

**Comment by SomebodyNameMe** [comment]
gitee有导入其它链接仓库的功能啊,登录之后从右上角加号，选择从github导入仓库
