### ISSUE TITLE
java怎么调用啊.....

### ISSUE THREAD

**Issue by 50kg** [shenzhen2017/EasyFloat#9]
listener不会了

**Comment by RicardoJiang** [comment]
大概类似这样

```java
public class Test {
    public void test() {
        EasyFloat.INSTANCE
                .layout(R.layout.layout_float_view)
                .listener(new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        return null;
                    }
                }, new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        return null;
                    }
                });
    }
}
```

**Comment by 50kg** [comment]
我是这样写的，不太管用呀， public Unit invoke(View view) {，这个view是指的layout_float_view吗？

EasyFloat.INSTANCE
                .layout(R.layout.layout_float_view)
                .dragEnable(true)
                .setAutoMoveToEdge(true)
                .listener(new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        LogUtil.e(TAG, "invoke1：def");
                        View rootView = view.findViewById(R.id.ll_root);
                        view.findViewById(R.id.btn).setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                LogUtil.e(TAG, "invoke1：def 123");
                            }
                        });
                        return null;
                    }
                }, new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        LogUtil.e(TAG, "invoke2：def");
                        View rootView = view.findViewById(R.id.ll_root);
                        view.findViewById(R.id.btn).setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                LogUtil.e(TAG, "invoke2：def 456");
                            }
                        });
                        return null;
                    }
                })
                .show(this);

**Comment by RicardoJiang** [comment]
```java
public class FourthActivity extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void show(View view){
        EasyFloat.INSTANCE.layout(R.layout.layout_float_view)
                .dragEnable(true)
                .listener(new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        return null;
                    }
                }, new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        View rootView = view.findViewById(R.id.ll_root);
                        rootView.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                Log.i("tiaoshi","here");
                            }
                        });
                        return null;
                    }
                })
                .show(this);
    }
}
```

**Comment by RicardoJiang** [comment]
效果如图所示，view就是R.layout.layout_float_view创建的view
![image](https://user-images.githubusercontent.com/18047645/139063772-1e6f2acf-15d7-4833-abd5-70a7de9d7c2b.png)
